### ISSUE TITLE
Render LaTeX math

### ISSUE THREAD

**Issue by mstksg** [theam/tintin#19]
Hi, thank you for the great package!

Was thinking that it would be nice if tintin had the ability to render LaTeX math from markdown source, with mathjax or some other method perhaps :)  Haddock does this I believe, and the pandoc markdown processor allows for mathjax preprocessing (and other sources) as well.

**Comment by ocramz** [comment]
KaTeX too seems very promising! https://khan.github.io/KaTeX/

**Comment by J2RGEZ** [comment]
I can work on this! :+1:
