### ISSUE TITLE
Next/Prev buttons

### ISSUE THREAD

**Issue by mstksg** [theam/tintin#23]
Hi!  Was wondering if it would be too much to implement automatic "Next"/"Prev" buttons for pages, like they have in readthedocs and similar systems?  Right now i'm [putting them in by hand][byhand] at the end of my documents.

[byhand]: https://backprop.jle.im/01-getting-started.html

I can give a shot at trying to implement them myself, but was wondering if there were any opinions on how they should be styled.

**Comment by NickSeagull** [comment]
Hey there! Thanks for this issue :smile: 

Making some Next/Prev functions would be very easy to make. I think they could be in the footer of the docs.

We could have some string like `< Previous: title of previous page` and `Next: title of next page >`. It would have the same color as the `2018 (C)` string. What do you think?
