### ISSUE TITLE
tintin doesn't work without github

### ISSUE THREAD

**Issue by locallycompact** [theam/tintin#26]
Hi, I was surprised to see this error

    [ERROR] - "Project must be hosted in a Github repository. Please set it in package.yaml or *.cabal."

Why is this necessary? I just want the static site generation so I can upload it to gitlab pages.

**Comment by NickSeagull** [comment]
Thanks for reporting this issue!

We've made it as simple as possible, as most Haskell projects are hosted on Github :smile: 
Adding support for other things apart from Github should be really easy, feel free to ping me if you need help implementing it ^_^

**Comment by wiz** [comment]
> We've made it as simple as possible, as most Haskell projects are hosted on Github

And this is a part of the problem.  Tools go GitHub-first (or even GitHub-only) and tilt incentives further towards monoculture )=

**Comment by NickSeagull** [comment]
This is true @wiz , these days, after all the M$ stuff, I thought about all of this, and definitely it is not good

Btw, closing, as this was fixed in #28
