### ISSUE TITLE
Strange build failure on Stackage

### ISSUE THREAD

**Issue by jkachmar** [theam/tintin#38]
I'm not entirely sure what's causing this, since I'm only encountering it on the Stackage build server and not locally, but for some reason it appears that `tintin-1.9.1` fails to build with the following error:

```
[13 of 18] Compiling Tintin.ConfigurationLoading ( src/Tintin/ConfigurationLoading.hs, dist/build/Tintin/ConfigurationLoading.o )

src/Tintin/ConfigurationLoading.hs:59:1: error:
    lexical error in string/character literal at character '{'
   |
59 |                            \\n\nTry creating .tintin.yml and adding color:blue to it."])
   | ^
```

Have you seen this before at all?

**Comment by lukehoersten** [comment]
https://matrix.hackage.haskell.org/package/tintin been broken since 1.2.5. Any fix schedule?

**Comment by NickSeagull** [comment]
With #39 the error should be fixed in Hackage/Stackage, please let me know @lukehoersten @jkachmar

**Comment by NickSeagull** [comment]
I've removed even more multiline strings. https://matrix.hackage.haskell.org/package/tintin should be fixed now.

**Comment by NickSeagull** [comment]
Fixing require so we can upload tintin also

**Comment by andreabedini** [comment]
just a drive-by comment to confirm that `cabal new-install tintin-1.9.5` builds correctly for me.

**Comment by NickSeagull** [comment]
Tintin builds on Stackage now as https://github.com/commercialhaskell/stackage/pull/4318 .
 
I think this can be closed now, thanks everyone!
