### ISSUE TITLE
Incomplete pattern-matching error on empty index.md

### ISSUE THREAD

**Issue by wiz** [theam/tintin#42]
```
tintin: src/Tintin/Domain/DocumentationFile.hs:(22,3)-(34,9): Non-exhaustive patterns in case
```

Indeed, `tintin` only matches `Fail` and `Done` while `frontmatter` also has [Partial](https://hackage.haskell.org/package/frontmatter-0.1.0.2/docs/Data-Frontmatter.html#t:IResult).

You may wish to handle this constructor too or switch to `parseYamlFrontmatterEither` and remove the result-formatting code.

**Comment by NickSeagull** [comment]
Thanks for reporting the issue! :pray: :smile: 

This has been resolved in #44
