### ISSUE TITLE
Generate social meta tags

### ISSUE THREAD

**Issue by javiertoledo** [theam/tintin#5]
It would be nice if tintin could generate the social meta tags to show a beautiful preview of haskell libraries on social networks :-)

Some more details here:
https://moz.com/blog/meta-data-templates-123

**Comment by NickSeagull** [comment]
Sounds awesome, let's see if I can come up with some interesting way of doing so :smile:

**Comment by J2RGEZ** [comment]
I will try to make this :+1:

**Comment by J2RGEZ** [comment]
Fixed!
