### ISSUE TITLE
Add option to specify package file

### ISSUE THREAD

**Issue by wiz** [theam/tintin#51]
I want to switch to a multi-package repository while maintaining a single doc site.

Running `tintin` with the package moved into a subfolder gives an error:
```
[ERROR] - "No package.yaml or *.cabal file found."
```

However, symlinking `subdir/package.yaml` back into root allows `tintin` to proceed.

I would rather have to specify the path explicitly than have a dangling `package.yaml` (or separate `package-doc`) as long as it has no ill effects.

**Comment by NickSeagull** [comment]
Thanks! The idea is very nice, in fact I have encountered this issue in the past, just that I created a separate doc package.

Let me think how I'd go implementing this.

**Comment by javiertoledo** [comment]
I was thinking that for multi-package support we could just make `package.yaml` and `*.cabal` files optional and fallback to Tintin's own config file when none of them are present. What I'm not sure about is how that could affect the syntax checks in code blocks, can you import multiple packages? should that work? I've been playing with the code a little bit in a local branch and I think it's a relatively easy change and as we need to reimplement a few things we could go ahead and include #52 and #57 in the refactor. How does that sound?

**Comment by wiz** [comment]
I'm not in any hurry (:

**Comment by NickSeagull** [comment]
Hmm, that does sound very interesting @javiertoledo, what Tintin does under the hood is:

* It is run from a Stack environment
* Calls GHC for compilation
* Applies a Markdown to Haskell conversion (using the inliterate library) by:
  * Generating a `main` function that prints all the `eval` blocks
  * Generating a top level definition per `top` block
* Then it runs this as an executable, returning an HTML-ish value
* Tintin captures this and injects all its CSS and structure

What I'm not really sure about is how would tintin work outside of a project.

Perhaps, it should have it's own project definition in its config file, and generate a project under the hood just for rendering the docs?

**Comment by javiertoledo** [comment]
🤔 Okay, let's start then by just allowing the user to override the values in the `package.yaml` so you can have a special project for your docs as you mentioned or use a different umbrella project or whatever

**Comment by NickSeagull** [comment]
Solved in #58
