### ISSUE TITLE
Doesn't seem to work without JS

### ISSUE THREAD

**Issue by aminb** [theam/tintin#7]
I use uMatrix and enable JS only selectively for the websites I visit. As of now, without JS, both the Home and Docs pages of the project website are mostly blank and void of any content, as seen below:

- Home: https://screenshots.firefox.com/jOIvj68eXJppnxOH/theam.github.io
- Docs: https://screenshots.firefox.com/WV2cKpLX8uzixWVy/theam.github.io

It would be nice to have tintin work without requiring JS, at least for displaying the non-interactive parts.

**Comment by NickSeagull** [comment]
Uh, yes. Tintin uses an _animate on scroll_ JS library. Do you have any ideas on how to disable it if JS is not enabled? :smile:

**Comment by aminb** [comment]
Aha. I'm not really sure about how to do that. I had a quick skim through the library's docs and their github issues but couldn't find anything relevant.

Thinking about it, if the library is only tasked with animating the content and not fetching it, the issue is probably that the content is initially hidden using CSS but the library isn't able to un-hide it by manipulating that CSS using JS.

**Comment by NickSeagull** [comment]
Interesting! Will check this out and try to fix it :smile:

**Comment by ocramz** [comment]
I know this may sound like heresy nowadays, but what do you think of getting rid of CSS transitions and JS trickery altogether, to be friendlier to older clients, sandboxed environments etc.? Just plain old HTML documentation

**Comment by aminb** [comment]
:+1: for getting rid of JS trickery, especially if it hinders with user experience in absence of JS.

If you like to keep transitions, I suggest looking into [Animate.css](https://daneden.github.io/animate.css/), which is a CSS animation library that seems to work just fine without JS. Note: changing the animation preview on their demo page I linked above requires JS but page-load animations seem to work fine without it.

**Comment by aminb** [comment]
Works great! Thanks for the fix @NickSeagull.

**Comment by NickSeagull** [comment]
You're welcome :grin:
