### ISSUE TITLE
Elaborate on why not RTD?

### ISSUE THREAD

**Issue by michaelpj** [theam/tintin#75]
This looks like a cool project!

I was surprised to read the section in the readme that suggests not to use RTD because it won't compile your code. This is true, but it's not too hard to get around - I've been doing it for quite a while and it works nicely!

The way you do it is like this:
- Write your Haskell code in `.hs` files next to your doc files.
- Include segments of the Haskell file into your doc files at appropriate places with the `literalinclude` directive.
- Make your doc folder into a `cabal` package so that you can compile/test the source files to check that they work.

I'm interested whether there are other killer features of tintin, since otherwise it seems like the ecosystem advantage of RTD is pretty big?

**Comment by dpwiz** [comment]
What's the "ecosystem advantage of RTD"?

**Comment by michaelpj** [comment]
You're using sphinx which has lots of plugins, documentation, etc.

**Comment by dpwiz** [comment]
So, it is actually "why not Sphinx"?

**Comment by NickSeagull** [comment]
Hey! Thanks for bringing this up!

Perhaps the words written in the README weren't the correct ones, but to elaborate a bit more:

The idea behind Tintin is to have inline code in markdown files, making it easier to manage the docs. Note how to achieve the same result in RTD/Sphinx, one has to do the multiple steps that you've described.

Of course, it is the correct way of using RTD, but most users would probably skip all of that, and just write the code snippets inline in the code. I had this exact problem in another project with contributors to the repo, and I had to either make the appropriate changes manually myself, or ask them to make the change in the doc, get a "Yes, give me a couple of days" and in the 90% of the cases make the change myself 😆 (Not blaming contributors, life is life, and they did enough effort by submitting a PR with doc changes)

So again, the point of Tintin is to make all of this automatic, so users only have to write docs and nothing else.

Maybe a feature could be integration with RTD or something :)

**Comment by michaelpj** [comment]
Right, having the source inline in the file is a nice feature for sure. Probably not enough to tempt me away, though :)

**Comment by NickSeagull** [comment]
Closing this as it looks it was solved :)
